### ISSUE TITLE
Failed to create pwnBundle for device=iPhone7,1 buildnum=16G130

### ISSUE THREAD

**Issue by arinc9** [tihmstar/ra1nsn0w#2]
```
Arncs-iMac:rain arinc9$ ra1nsn0w -t /Users/arinc9/Desktop/rain/7082839438483494_iPhone7\,1_12.4.3-16G130_080aafada2d237541a5ce42d36400bd8af8dd4a1.shsh2 -B 16G130 -b "-v"
ra1nsn0w version: 0.3-29debd6770c9929d826ea24c6cd632d161f015f3
img4tool version: 0.163-c3df16cb998d5013aef092baeb71908475366182
libfragmentzip version: 0.58-ffec726ea514d8b8f3f3e42d04ce1430f3889747
Libipatcher Version: eaab687b56fe8147076814bd377b0e9aa49a04fb - 65
Waiting for device...
No IPSW specified, getting URL to ipsw by buildid
ra1nsn0w: failed with exception:
[exception]:
what=Failed to create pwnBundle for device=iPhone7,1 buildnum=16G130
code=47841295
line=730
file=libipatcher.cpp
commit count=26:
commit sha  =4c96389db50eeb7411f6e4c62eb073ef401ca6bd:
```

Edit: I hate it when such great tools lack documentation. Turns out by looking at Tihmstar's tweets the device needs to be in pwneddfu mode and have sigchk-patches which is only on linushenze's ipwndfu fork. Then run a local webserver for libipatcher to find the firmware keys for these devices. This is too many steps to be gone undocumented. 

I’ll actually be writing a tutorial of how to use ra1nsn0w and to compile it properly.

Final: After countless hours of mindblowing and teamviewer'ing each other with @anonfantom, we've finally realized that signature check remover from @LinusHenze does not support our device (t8010) after we've spent hours into finding firmware keys and making a bundle file for it one by one. Yay

Anyway the issue's been solved but I'll let this stay open for a while until it gets some recognition.

**Comment by DaJakerBoss** [comment]
Maybe try getting your own ipsw and manually specifying

**Comment by abuhassan-dev** [comment]
@arinc9 I've got an error when compiling on Catalina 
can you share the release or tell me how to fix compiling prosses?

**Comment by arinc9** [comment]
@DaJakerBoss Can you give more details, please?
@anonfantom it's dynamically linked so you couldn't use it, contact me at somewhere else (eg. Twitter DM, @arincjb9) so we won't discuss unrelated to the issue.

**Comment by arinc9** [comment]
@DaJakerBoss ~~Do you think device needs to be in pwneddfu mode to use this?~~

**Comment by tihmstar** [comment]
Yes the device does need to be in pwnDfu and have sigcheck patches.
If no keys are available for your device on ipsw.me you can try
[wikiproxy](https://github.com/tihmstar/libipatcher/blob/master/wikiproxy.py) to grab them from theiphonewiki instead.

If theiphonewiki doesn't have them either, you need to manually create a bundle which looks like
this: https://firmware-keys.ipsw.me/firmware/iPhone6,2/14G60 and put it on a local webserver which should run on port 8888.
The device will then try to grab a bundle from localhost:8888/\<device\>/\<build\> 
which is http://localhost:8888/iPhone6,2/14G60 
If you run on iPhone6,2 with Buildnum 14G60.

**Comment by arinc9** [comment]
@tihmstar there are lots of keys to find to create a bundle completely, shouldn't finding iBoot, iBSS, iBEC be enough for ra1nsn0w to work? Also using checkm8 to find the keys, will these keys only work for that one unique device or every device with the same model?

**Comment by arinc9** [comment]
@tihmstar do you also know how we can just get the bundle file from iphonedevwiki like from ipsw.me (i.e. https://firmware-keys.ipsw.me/firmware/iPad7,5/16F203), using the wikiproxy.py?

**Comment by arinc9** [comment]
After countless hours of mindblowing and teamviewer'ing each other with @anonfantom, we've finally realized that signature check remover from @LinusHenze does not support our device (t8010) after we've spent hours into finding firmware keys and making a bundle file for it one by one. Yay

Anyway the issue's been solved but I'll let this stay open for a while until it gets some recognition.
