### ISSUE TITLE
How should I compile this?

### ISSUE THREAD

**Issue by flash76** [tihmstar/ra1nsn0w#3]
I tried doing a number of things. First I tried downloading all of the tihmstar libraries and putting them in the include directory for Xcode but that didn't work, so I followed the directions of someone on a reply to the ra1nsn0w post, which told me to clone recursively and do ./autogen.sh && make. When I do that, at the end I get 
`./configure: line 16352: syntax error near unexpected token 'libfragmentzip,'
./configure: line 16352: 'PKG_CHECK_MODULES(libfragmentzip, libfragmentzip >= 58)'`

Tried on macOS 10.15.2

**Comment by arinc9** [comment]
Here's a few tricks about compiling tihmstar's software

drive.google.com/open?id=1rItlj2vdu35UrxcdlamJOktvIEhyy1yK
compile these in the archive (they don't get updated often) put library and headers to correct directories and git clone --recursive these: libipatcher, libfragmentzip, liboffsetfinder64, img4tool, libgeneral

If you still can't figure it out DM me on Twitter (@arincjb9)

**Comment by cakarlen** [comment]
I'm having troubles compiling libipatcher. Can anyone provide these libs?

**Comment by arinc9** [comment]
@cakarlen what's the error you're getting?

**Comment by cakarlen** [comment]
@arinc9 I try to compile ra1nsn0w itself and it depends on libipatcher. When I compile libipatcher, I get `configure: error: requested building with iBoot64Patcher, but liboffsetfinder64 could not be found`

I know for a fact I have compiled/installed liboffsetfinder64 so I'm confused at this point.

**Comment by arinc9** [comment]
tihmstar keeps updating his projects you need to keep them updated mate

**Comment by flash76** [comment]
@arinc9 Is the stuff in the linked archive already compiled? Or should I compile those and then clone the other repos mentioned and add the libraries to Xcode and compile from there?

**Comment by cakarlen** [comment]
@arinc9 I already git pulled all the other dependencies and they are up to date

**Comment by arinc9** [comment]
they're not compiled, configure and make install the archive first, then add the libraries to /usr/local/lib, headers to /usr/local/include then compile git clone projects

**Comment by arinc9** [comment]
@cakarlen you also need to make install the updated versions that means re "./configure-./autogen.sh" and make install'ing them.

**Comment by flash76** [comment]
How should I compile this? When I run ./configure, at the end I'm told
`./configure: line 12820: syntax error near unexpected token 'curl,'` even though curl is installed. I'm pretty sure this would happen if I go about configuring the other projects in the futurerestoreMac folder.

**Comment by arinc9** [comment]
install libcurl too then try again

**Comment by The-SamminAter** [comment]
Is there a place that one could obtain the compiled software from, and if not, can a copy please be shared for people who can't compile it for various reasons?

**Comment by arinc9** [comment]
It's been a while since my effort on this but to actually make use of a copy of the binary, it needs to be compiled statically. Meaning the libraries i.e. futurerestore uses should be already included in the binary. I remember I've run into issues while statically compiling futurerestore. (Come to think of it; I probably didn't need to statically compile the dependencies, maybe that's why I've run into issues in the first place.)

Anyway, I got an old archive laying around. It should help you figuring out the dependencies if you're planning on working further on this.
https://drive.google.com/open?id=1rItlj2vdu35UrxcdlamJOktvIEhyy1yK

**Comment by The-SamminAter** [comment]
Thanks for sharing, but I honestly was not planning to work on it. 

I was more hoping that I could just use it, hopefully without spending hours upon hours trying to make it work.

**Comment by arinc9** [comment]
Welp good luck on that mate. I've never got help from anyone so consider yourself lucky if someone gives you a hand on this.

**Comment by The-SamminAter** [comment]
Wait, is buildroot_macos-latest.zip and buildroot_ubuntu-latest.zip (from the latest release) compiled and ready-to-run?

**Comment by arinc9** [comment]
You're in luck. Looks like tihm's published the prebuilt binary on Jan 4.
