### ISSUE TITLE
Kernelcache de-compression failure iPhone10,3  b16g77 (12.4)

### ISSUE THREAD

**Issue by CorporateWoes** [tihmstar/ra1nsn0w#4]
I got this compiled correctly and am running wiki proxy no problem, but ra1nsn0w's failing when I get to the  stage below. Searched source code, couldn't find the origin of the error message to try and remedy the situation, so figured it would be worth a post here.

> Computer:ra1nsn0w User$ ./ra1nsn0w -t *.shsh2 *.ipsw -b "-v"
ra1nsn0w version: 0.5-974c4407f7bd3581b15ee7e862f673ad5271b13c
img4tool version: 0.163-c3df16cb998d5013aef092baeb71908475366182
libfragmentzip version: 0.58-ffec726ea514d8b8f3f3e42d04ce1430f3889747
Libipatcher Version: 80df8700f52e6eb8777a28bfcc19f86da7d9b9b9 - 68
Waiting for device...
Found device: iPhone10,3
Got local ipsw path=iPhone10,3,iPhone10,6_12.4_16G77_Restore.ipsw
Opening firmware...
Loading BuildManifest...
Getting Firmware Keys...
Found iBSS at Firmware/dfu/iBSS.d22.RELEASE.im4p
Found iBEC at Firmware/dfu/iBEC.d22.RELEASE.im4p
Found kernel at kernelcache.release.iphone10b
Found DeviceTree at Firmware/all_flash/DeviceTree.d22ap.im4p
Loading iBSS...
Loading iBEC...
Loading kernel...
Loading DeviceTree...
Patching iBSS...
Kernelcache detected, uncompressing (bvx2): failed!
[WARNING] Unpacking bvx2 currently not implemented!

>ra1nsn0w: failed with exception:
[exception]:
what=assure failed
code=22675471
line=346
file=libipatcher.cpp
commit count=26:
commit sha  =4c96389db50eeb7411f6e4c62eb073ef401ca6bd:
Computer:ra1nsn0w User$

**Comment by dlash000** [comment]
> I got this compiled correctly and am running wiki proxy no problem, but ra1nsn0w's failing when I get to the stage below. Searched source code, couldn't find the origin of the error message to try and remedy the situation, so figured it would be worth a post here.
> 
> > Computer:ra1nsn0w User$ ./ra1nsn0w -t *.shsh2 *.ipsw -b "-v"
> > ra1nsn0w version: 0.5-974c4407f7bd3581b15ee7e862f673ad5271b13c
> > img4tool version: 0.163-c3df16cb998d5013aef092baeb71908475366182
> > libfragmentzip version: 0.58-ffec726ea514d8b8f3f3e42d04ce1430f3889747
> > Libipatcher Version: 80df8700f52e6eb8777a28bfcc19f86da7d9b9b9 - 68
> > Waiting for device...
> > Found device: iPhone10,3
> > Got local ipsw path=iPhone10,3,iPhone10,6_12.4_16G77_Restore.ipsw
> > Opening firmware...
> > Loading BuildManifest...
> > Getting Firmware Keys...
> > Found iBSS at Firmware/dfu/iBSS.d22.RELEASE.im4p
> > Found iBEC at Firmware/dfu/iBEC.d22.RELEASE.im4p
> > Found kernel at kernelcache.release.iphone10b
> > Found DeviceTree at Firmware/all_flash/DeviceTree.d22ap.im4p
> > Loading iBSS...
> > Loading iBEC...
> > Loading kernel...
> > Loading DeviceTree...
> > Patching iBSS...
> > Kernelcache detected, uncompressing (bvx2): failed!
> > [WARNING] Unpacking bvx2 currently not implemented!
> 
> > ra1nsn0w: failed with exception:
> > [exception]:
> > what=assure failed
> > code=22675471
> > line=346
> > file=libipatcher.cpp
> > commit count=26:
> > commit sha  =4c96389db50eeb7411f6e4c62eb073ef401ca6bd:
> > Computer:ra1nsn0w User$

**Comment by dlash000** [comment]
> I got this compiled correctly and am running wiki proxy no problem, but ra1nsn0w's failing when I get to the stage below. Searched source code, couldn't find the origin of the error message to try and remedy the situation, so figured it would be worth a post here.
> 
> > Computer:ra1nsn0w User$ ./ra1nsn0w -t *.shsh2 *.ipsw -b "-v"
> > ra1nsn0w version: 0.5-974c4407f7bd3581b15ee7e862f673ad5271b13c
> > img4tool version: 0.163-c3df16cb998d5013aef092baeb71908475366182
> > libfragmentzip version: 0.58-ffec726ea514d8b8f3f3e42d04ce1430f3889747
> > Libipatcher Version: 80df8700f52e6eb8777a28bfcc19f86da7d9b9b9 - 68
> > Waiting for device...
> > Found device: iPhone10,3
> > Got local ipsw path=iPhone10,3,iPhone10,6_12.4_16G77_Restore.ipsw
> > Opening firmware...
> > Loading BuildManifest...
> > Getting Firmware Keys...
> > Found iBSS at Firmware/dfu/iBSS.d22.RELEASE.im4p
> > Found iBEC at Firmware/dfu/iBEC.d22.RELEASE.im4p
> > Found kernel at kernelcache.release.iphone10b
> > Found DeviceTree at Firmware/all_flash/DeviceTree.d22ap.im4p
> > Loading iBSS...
> > Loading iBEC...
> > Loading kernel...
> > Loading DeviceTree...
> > Patching iBSS...
> > Kernelcache detected, uncompressing (bvx2): failed!
> > [WARNING] Unpacking bvx2 currently not implemented!
> 
> > ra1nsn0w: failed with exception:
> > [exception]:
> > what=assure failed
> > code=22675471
> > line=346
> > file=libipatcher.cpp
> > commit count=26:
> > commit sha  =4c96389db50eeb7411f6e4c62eb073ef401ca6bd:
> > Computer:ra1nsn0w User$
